### ISSUE TITLE
AMAP_WEB_KEY不写出来咋用哦

### ISSUE THREAD

**Issue by spencercjh** [c0ldcat/Auto-Run#1]
gradle中 buildConfigField("String", "AMAP_WEB_KEY", AutoRunAMapWebKey),你这个AutoRunAMapWebKey不交出来，咋用哦？

**Comment by ccat3z** [comment]
去高德地图那注册一个啊

**Comment by ccat3z** [comment]
我要不要贴个教程

**Comment by spencercjh** [comment]
要的 ！！！我只会普通的android开发，hook完全没接触过，我build完项目看都没法运行，嘤嘤嘤

**Comment by ccat3z** [comment]
那我晚上回去补个教程...

**Comment by spencercjh** [comment]
我自己琢磨出来了，你可以看看我的：https://github.com/spencercjh/gxtyHack
